# global:
#   scrape_interval: 15s # Adjust the scraping frequency if needed

# scrape_configs:
#   - job_name: 'node_app'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['localhost:3000'] # Your Node.js app metrics endpoint

global:
  scrape_interval: 15s
remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 
      password: 
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:3000"]
